name: 'Log Environment'
description: 'Logs environment variables for a job'
runs:
  using: "composite"
  steps:
    - run: |
        echo ""
        echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
        echo "GITHUB_REF: $GITHUB_REF"
        echo "github.head_ref: ${{ github.head_ref }}"
        echo ""
        echo "github.event.inputs.environment: ${{ github.event.inputs.environment }} (default: ${{ env.DEFAULT_ENVIRONMENT }})"
        echo "github.event.inputs.action: ${{ github.event.inputs.action }} (default: ${{ env.DEFAULT_ACTION }})"
      shell: bash
