AWSTemplateFormatVersion: '2010-09-09'
Description: ACFS3 - Certificate creation

Parameters:
  DomainName:
    Type: String
  SubDomain:
    Type: String
  CreateApex:
    Type: String
  HostedZoneId:
    Type: String
  Environment:
    Type: String
    Description: 'Environment name'
    AllowedValues:
      - dev
      - staging
      - prod

Conditions:
  CreateApexConfig: !Equals
    - !Ref CreateApex
    - 'yes'

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub '${SubDomain}.${DomainName}'
      SubjectAlternativeNames:
        Fn::If:
          - CreateApexConfig
          - - Ref: DomainName
          - Ref: AWS::NoValue
      DomainValidationOptions:
        - DomainName: !Sub '${SubDomain}.${DomainName}'
          HostedZoneId: !Ref HostedZoneId
        - Fn::If:
            - CreateApexConfig
            - DomainName: !Ref DomainName
              HostedZoneId: !Ref HostedZoneId
            - Ref: AWS::NoValue
      ValidationMethod: DNS
      Tags:
        - Key: Solution
          Value: ACFS3
        - Key: Environment
          Value: !Ref Environment
      
Outputs:
  CertificateArn:
    Description: Issued certificate
    Value: !Ref Certificate
