AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Roles and OIDC Provider for GitHub Actions CI/CD

Parameters:
  Name:
    Type: String
    Description: Project or application name

  GitHubOrg:
    Type: String
    Description: GitHub organization or username

  GitHubRepo:
    Type: String
    Description: GitHub repository name

  Environment:
    Type: String
    Description: Environment name
    AllowedValues:
      - dev
      - staging
      - prod
    Default: dev

Resources:
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Name}-github-actions-${Environment}-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub 'repo:${GitHubOrg}/${GitHubRepo}:*'
                # token.actions.githubusercontent.com:sub: 
                #   - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:ref:refs/heads/main'
                #   - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:ref:refs/heads/master'
                #   - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:ref:refs/heads/develop'
                #   - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:environment:development'
                #   - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:environment:staging'
                #   - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:environment:production'
                #   - !Sub 'repo:${GitHubOrg}/${GitHubRepo}:pull_request'
      ManagedPolicyArns:
        - !Ref GitHubActionsPolicy
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: GitHubActions

  GitHubActionsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub '${Name}-github-actions-${Environment}-policy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:CreateStack
              - cloudformation:UpdateStack
              - cloudformation:DeleteStack
              - cloudformation:DescribeStacks
              - cloudformation:CreateChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:DeleteChangeSet
              - cloudformation:DescribeChangeSet
              - cloudformation:GetTemplate
              - cloudformation:ValidateTemplate
              - cloudformation:Package
              - cloudformation:Deploy
            Resource: '*'
          - Effect: Allow
            Action:
              - s3:CreateBucket
              - s3:DeleteBucket
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
              - s3:GetBucketLocation
              - s3:GetBucketVersioning
              - s3:PutBucketVersioning
              - s3:GetBucketEncryption
              - s3:PutBucketEncryption
              - s3:GetBucketPolicy
              - s3:PutBucketPolicy
              - s3:DeleteBucketPolicy
              - s3:GetBucketLogging
              - s3:PutBucketLogging
              - s3:GetBucketWebsite
              - s3:PutBucketWebsite
              - s3:DeleteBucketWebsite
            Resource: '*'
          - Effect: Allow
            Action:
              - route53:GetHostedZone
              - route53:ListHostedZones
              - route53:ChangeResourceRecordSets
              - route53:ListResourceRecordSets
            Resource: '*'
          - Effect: Allow
            Action:
              - acm:RequestCertificate
              - acm:DescribeCertificate
              - acm:DeleteCertificate
              - acm:ListCertificates
              - acm:AddTagsToCertificate
              - acm:RemoveTagsFromCertificate
            Resource: '*'
          - Effect: Allow
            Action:
              - cloudfront:CreateDistribution
              - cloudfront:UpdateDistribution
              - cloudfront:DeleteDistribution
              - cloudfront:GetDistribution
              - cloudfront:ListDistributions
              - cloudfront:CreateInvalidation
              - cloudfront:GetInvalidation
              - cloudfront:ListInvalidations
            Resource: '*'
          - Effect: Allow
            Action:
              - iam:PassRole
            Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/*'
          - Effect: Allow
            Action:
              - iam:CreateRole
              - iam:DeleteRole
              - iam:GetRole
              - iam:UpdateRole
              - iam:CreatePolicy
              - iam:DeletePolicy
              - iam:GetPolicy
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
              - iam:PutRolePolicy
              - iam:DeleteRolePolicy
              - iam:GetRolePolicy
              - iam:CreateInstanceProfile
              - iam:DeleteInstanceProfile
              - iam:AddRoleToInstanceProfile
              - iam:RemoveRoleFromInstanceProfile
            Resource: '*'
          - Effect: Allow
            Action:
              - lambda:CreateFunction
              - lambda:UpdateFunctionCode
              - lambda:UpdateFunctionConfiguration
              - lambda:GetFunction
              - lambda:DeleteFunction
              - lambda:InvokeFunction
              - lambda:ListFunctions
            Resource: '*'
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
            Resource: '*'
          - Effect: Allow
            Action:
              - sts:GetCallerIdentity
            Resource: '*'

Outputs:
  GitHubActionsRoleArn:
    Description: ARN of the GitHub Actions IAM role
    Value: !GetAtt GitHubActionsRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RoleArn'
